# Generated by Django 5.2.1 on 2025-06-02 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id_comunidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'comunidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id_distrito', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'distrito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id_calle', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('id_comunidad', models.ForeignKey(db_column='id_comunidad', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.comunidad')),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.departamento')),
                ('id_distrito', models.ForeignKey(db_column='id_distrito', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.distrito')),
            ],
            options={
                'db_table': 'calle',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='comunidad',
            name='id_distrito',
            field=models.ForeignKey(db_column='id_distrito', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.distrito'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=150, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=150, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_usuario', models.CharField(blank=True, choices=[('buscar-trabajo', 'Buscar trabajo'), ('ofrecer-trabajo', 'Ofrecer trabajo'), ('ambos', 'Buscar y ofrecer trabajo'), ('empresa', 'Como empresa')], max_length=30, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_calle', models.ForeignKey(blank=True, db_column='id_calle', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.calle')),
                ('id_comunidad', models.ForeignKey(blank=True, db_column='id_comunidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.comunidad')),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.departamento')),
                ('id_distrito', models.ForeignKey(blank=True, db_column='id_distrito', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.distrito')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('email_empresa', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('clave', models.CharField(max_length=128)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles_empresas/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empresa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.departamento')),
            ],
            options={
                'db_table': 'provincia',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='distrito',
            name='id_provincia',
            field=models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.provincia'),
        ),
        migrations.AddField(
            model_name='calle',
            name='id_ciudad',
            field=models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.provincia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_provincia',
            field=models.ForeignKey(blank=True, db_column='id_provincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.provincia'),
        ),
    ]
